# This is a basic workflow to help you get started with Actions

name: Revanced

# Allows you to run this workflow manually from the Actions tab
on: [workflow_dispatch, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialization environment
        run: |
          sudo apt update
          sudo apt install git
          python3 -m pip install telethon
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Start building
        env:
          APPID: ${{ secrets.APPID }}
          APIHASH: ${{ secrets.APIHASH }}
          SESSIONSTRING: ${{ secrets.SESSIONSTRING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./yt.sh
